const types= {
    GET_TODOS: 'GET_TODOS',
    SET_ACTION_ACTIVE: 'SET_ACTION_ACTIVE',
    SET_MODAL_FORM: 'SET_MODAL_FORM',
    CLOSE_MODAL_FORM: 'CLOSE_MODAL_FORM',
    SET_MODAL_ADD: 'SET_MODAL_ADD',
    SET_MODAL_EDIT: 'SET_MODAL_EDIT',
    LOADING: 'LOADING'
}

export default types